---
- name: echo /var/config.yml variables
  hosts: localhost
  gather_facts: false
  tasks:
    - name: echo variables
      ansible.builtin.debug:
        var: hostvars['localhost']
    - name: output ssh config
      ansible.builtin.debug:
        msg: 
          - "Ansible Connection User: {{ansible_user}}"
          - "SSH Private Key: {{ansible_ssh_private_key_file}}"
      when: (ansible_user is defined) and (ansible_ssh_private_key_file is defined)
  tags:
    - never
    - debug

# Create state backend and  infrastructure using terraform
- name: create infrastructure
  hosts: localhost
  gather_facts: false
  tasks:
    - name: apply terraform_be_infra role
      include_role: 
        name: terraform_be_infra
      tags: provision # tag applied to specific task so that role subtasks can be tagged

# Pause until infrastructure is created, and hosts are accessible via ssh
- name: bring up hosts
  # the following isn't available until playbook runs and reports an error in the linter
  hosts: "{{ hostvars['localhost']['project_group'] }}"

  # Force Loading of group_vars/all.yml because it was created during the terraform run
  # used to specify ansible_user and ssh key generated by terraform
  vars_files:
    - "{{ playbook_dir }}/group_vars/all.yml"
  gather_facts: false # gathering facts requires ssh connectivity
  tasks:
    - name: wait for hosts to be available
      # When accessing hosts newly created by terraform they may not be instantly available
      ansible.builtin.wait_for_connection:
        delay: 5
        sleep: 10
        timeout: 180
  tags:
    - provision

- name: verify host connectivity
  hosts: "{{ hostvars['localhost']['project_group'] }}"
  # Force Loading of group_vars/all.yml because it was created during the terraform run
  # used to specify ansible_user and ssh key
  vars_files:
    - "{{ playbook_dir }}/group_vars/all.yml"
  gather_facts: false
  tasks:
    - name: output ssh config
      ansible.builtin.debug:
        msg: 
          - "Ansible Connection User: {{ansible_user}}"
          - "SSH Private Key: {{ansible_ssh_private_key_file}}"
      when: (ansible_user is defined) and (ansible_ssh_private_key_file is defined)
    - name: ping hosts
      ansible.builtin.ping:
  tags:
    - never
    - debug

- name: common setup
  hosts: "{{ hostvars['localhost']['project_group'] }}"
  # Force Loading of group_vars/all.yml because it was created during the terraform run
  # used to specify ansible_user and ssh key
  vars_files:
    - "{{ playbook_dir }}/group_vars/all.yml"
  tasks:
    - name: run ec2_host_base role
      include_role:
        name: ec2_host_base
      vars:
        project_group: "{{ hostvars['localhost']['project_group'] }}"
  tags:
    - config
      
- name: destroy infrastructure
  hosts: localhost
  gather_facts: false
  tasks:
    - name: apply terraform_be_infra role
      include_role: 
        name: terraform_be_infra
      tags:
        - never
        - cleanup

